title: Director and playwright
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.9756788
  brandStrength: 0.3225806
  rhythmicContrast: 0.5
  brandColors:
    - '#0C0B0E'
    - '#778091'
    - '#FEFFFF'
    - '#65294A'
    - '#FFFBAB'
  lightness: 0.2329749
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: 'Morten Joachim '
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.6379929
layout_spectrum: 0.7849463
