collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.9756788
  brandStrength: 0.3225806
  rhythmicContrast: 0.02479051
  brandColors:
    - '#0C0B0E'
    - '#778091'
    - '#FEFFFF'
    - '#65294A'
    - '#FFFBAB'
  lightness: 0.2329749
typography_spectrum: 0.6379929
layout_spectrum: 0.8405018
name: mortenjoachim
